import "./globals.css";
import ConditionalLayout from "@components/ConditionalLayout";

export const metadata = {
  title: "WiFi Localization System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ConditionalLayout>{children}</ConditionalLayout>
      </body>
    </html>
  );
}
